name: Gaurav-Filerun
services:
  app:
    image: filerun/filerun:latest
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      TRANSMISSION_WEB_HOME: ''
      USER: ''
      PASS: ''
      WHITELIST: ''
      PEERPORT: ''
      HOST_WHITELIST: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: TRANSMISSION_WEB_HOME
          description:
            en_us: Specify the path to an alternative UI folder.
        - container: USER
          description:
            en_us: Specify an optional username for the interface
        - container: PASS
          description:
            en_us: Specify an optional password for the interface
        - container: WHITELIST
          description:
            en_us: Specify an optional list of comma separated ip whitelist. Fills rpc-whitelist setting.
        - container: PEERPORT
          description:
            en_us: Specify an optional port for torrent TCP/UDP connections. Fills peer-port setting.
        - container: HOST_WHITELIST
          description:
            en_us: Specify an optional list of comma separated dns name whitelist. Fills rpc-host-whitelist setting.
    ports:
      - target: 19091
        published: 9091
        protocol: tcp
      - target: 51413
        published: 51413
        protocol: tcp
      - target: 51413
        published: 51413
        protocol: udp
    volumes:
      - type: bind
        source: /DATA/AppData//filerun/html
        target: /var/www/html
      - type: bind
        source: /DATA/AppData/filerun/user-files
        target: /user-files
   links:
      - db:db
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/transmission/'
  tagline:
    en_us: 'Designed for easy, powerful use. Transmission has the features you want from a BitTorrent client: encryption, a web interface, peer exchange, magnet links, DHT, µTP, UPnP and NAT-PMP port forwarding, webseed support, watch directories, tracker editing, global and per-torrent speed limits, and more.'
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/transmission.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/transmission.png
  title:
    en_us: Transmission
  category: LinuxServer.io
  project_url: http://www.transmissionbt.com/
  port_map: '9091'
