name: Gaurav-Filerun
services:
  app:
    image: filerun/filerun:latest
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
      volumes:
        - container: /user-files
          description:
            en_us: Appdata
        - container: /var/www/html
           description:
            en_us: Appdata
      ports:
        - container: '3120'
          description:
            en_us: 'Container Port: 3120'
    ports:
      - target: 3120
        published: 80
        protocol: tcp

   volumes:
      - type: bind
        source: /DATA/AppData//filerun/html
        target: /var/www/html
      - type: bind
        source: /DATA/AppData/filerun/user-files
        target: /user-files
        
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/filezilla/'
  tagline:
    en_us: Client is a fast and reliable cross-platform FTP, FTPS and SFTP client with lots of useful features and an intuitive graphical user interface.
  developer: Gaurav
  author: Gaurav
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/filezilla-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/filezilla-logo.png
  title:
    en_us: Filerun
  category: Gaurav
  project_url: https://filezilla-project.org/
  port_map: '3120'


